# ==============================================
# 🚀 QuickServe Smart Startup Script (v1.0)
# ==============================================
# Author: OLOWOJARE & ChatGPT (Smart Sync Edition)
# Description: Automatically detects your IP, regenerates env-config.js,
# starts backend server, and opens frontend in browser.

Write-Host "`n💡 Starting QuickServe Smart Startup..." -ForegroundColor Cyan

# Detect your current LAN IPv4 address
$ip = (Get-NetIPAddress -AddressFamily IPv4 `
      | Where-Object { $.InterfaceAlias -notmatch "Loopback" -and $.IPAddress -notmatch "169\.254" } `
      | Select-Object -First 1 -ExpandProperty IPAddress)

if (-not $ip) { $ip = "127.0.0.1" }

$port = 5555
$frontendPath = "C:\Users\HP-PC\Desktop\quickserve\event-frontend\js\env-config.js"

# ==============================================
# 🔧 Regenerate env-config.js for Frontend
# ==============================================
$envConfig = @"
// Auto-generated by QuickServe Smart Startup
export const BACKEND_HTTP = 'http://$ip:$port';
export const API_BASE_URL = 'http://$ip:$port/api';
export const AUTH_API_URL = 'http://$ip:$port/api/auth';
export const SOCKET_URL = 'ws://$ip:$port';
export default { BACKEND_HTTP, API_BASE_URL, AUTH_API_URL, SOCKET_URL };
"@

try {
    Set-Content -Path $frontendPath -Value $envConfig -Encoding UTF8
    Write-Host "✅ Updated env-config.js successfully for $ip" -ForegroundColor Green
} catch {
    Write-Host "⚠ Could not update env-config.js: $_" -ForegroundColor Yellow
}

# ==============================================
# 🚀 Start Backend Automatically
# ==============================================
$backendPath = "C:\Users\HP-PC\Desktop\quickserve\backend"
Write-Host "`n🚀 Launching backend server..." -ForegroundColor Cyan
Start-Process powershell -ArgumentList "-NoExit", "-Command", "cd "$backendPath"; node server.js" `
    -WindowStyle Normal

# ==============================================
# 🌍 Open Frontend Automatically
# ==============================================
Start-Sleep -Seconds 4
$url = "http://${ip}:${port}/event-frontend/home.html"
Write-Host "`n🌐 Opening browser: $url" -ForegroundColor Cyan
Start-Process $url

Write-Host "`n✨ QuickServe Smart Startup complete!" -ForegroundColor Green
Write-Host "-----------------------------------------------"
Write-Host "✅ Backend Running on: http://${ip}:${port}"
Write-Host "✅ Frontend Opened: $url"
Write-Host "-----------------------------------------------"