Write-Host "`n🔄 Syncing QuickServe Frontend JS files..." -ForegroundColor Cyan

$root = "C:\Users\HP-PC\Desktop\quickserve\event-frontend\js"
$currentIP = "http://192.168.73.104:5555"

# Auto rebuild env-config.js with AUTH_API_URL included
$envFile = "$root\env-config.js"
@"
// Auto-generated by sync script
export const BACKEND_HTTP = '$currentIP';
export const API_BASE_URL = '$currentIP/api';
export const AUTH_API_URL = '$currentIP/api/auth';
export const SOCKET_URL = 'ws://192.168.73.104:5555';
export default { BACKEND_HTTP, API_BASE_URL, AUTH_API_URL, SOCKET_URL };
"@ | Set-Content $envFile -Encoding UTF8

# Update any JS import statements that reference config.js to remain local
Get-ChildItem -Path $root -Recurse -Include *.js | ForEach-Object {
    (Get-Content $_.FullName) -replace "/event-frontend/js/config.js", "./config.js" |
    Set-Content $_.FullName -Encoding UTF8
    Write-Host "✅ Synced:" $_.Name
}

Write-Host "`n✨ Frontend JS sync completed successfully!" -ForegroundColor Green