// ===============================
// 🚀 QuickServe Backend Server.js (Full Safe Version)
// ===============================

import express from "express";
import http from "http";
import cors from "cors";
import helmet from "helmet";
import dotenv from "dotenv";
import mongoose from "mongoose";
import { Server } from "socket.io";
import fs from "fs";
import path, { dirname, resolve, join } from "path";
import { fileURLToPath } from "url";
import vendorRoutes from "./routes/vendorRoutes.js";
import { ensurePendingOrderIndex } from "./models/PendingOrder.js";

// ==============================================
// 🔧 Environment Setup
// ==============================================
import dotenv from "dotenv";
dotenv.config({ path: join(__dirname, ".env") });

/// ==============================================
// 🧠 Utilities
// ==============================================
function detectLocalIp() {
  try {
    const nets = networkInterfaces();
    for (const name of Object.keys(nets)) {
      for (const net of nets[name]) {
        if (net.family === "IPv4" && !net.internal) return net.address;
      }
    }
  } catch (e) {
    console.warn("detectLocalIp error:", e.message);
  }
  return "127.0.0.1";
}

const LOCAL_IP = process.env.HOST_IP || detectLocalIp();
const PORT = process.env.PORT || 5555;
const BACKEND_HTTP = `http://${LOCAL_IP}:${PORT}`;
const BACKEND_WS = `ws://${LOCAL_IP}:${PORT}`;

console.log("🧭 Starting QuickServe backend");
console.log("🌐 Detected LOCAL_IP:", LOCAL_IP);
console.log("🧩 BACKEND_HTTP:", BACKEND_HTTP);
// ==============================================
// ⚙ Auto-run frontend sync PowerShell script on startup
// ==============================================
import { spawnSync } from "child_process";

try {
  const scriptPath = resolve(__dirname, "../auto-sync-frontend.ps1");
  console.log("🔄 Running frontend sync script:", scriptPath);
  
  const result = spawnSync("powershell", [
    "-ExecutionPolicy", "Bypass",
    "-File", scriptPath
  ], { encoding: "utf-8" });

  if (result.stdout) console.log(result.stdout);
  if (result.stderr) console.warn(result.stderr);

  console.log("✅ Frontend auto-sync complete before backend boot.\n");
} catch (err) {
  console.warn("⚠ Auto-sync script failed:", err.message);
}

// ============================================================
// 🧩 Auto-Sync Frontend JS (ESM-Safe + Windows Compatible)
// ============================================================
try {
  // ✅ Proper ESM path resolution (works on Windows too)
  const currentDir = dirname(fileURLToPath(import.meta.url));
  const frontendJsDir = resolve(currentDir, "../event-frontend/js");

  if (!fs.existsSync(frontendJsDir)) {
    fs.mkdirSync(frontendJsDir, { recursive: true });
  }

  // --- Build env-config.js dynamically ---
  const envConfigPath = join(frontendJsDir, "env-config.js");
  const envContent = `// Auto-generated by QuickServe backend
export const BACKEND_HTTP = 'http://${LOCAL_IP}:${PORT}';
export const API_BASE_URL = BACKEND_HTTP + '/api';
export const AUTH_API_URL = API_BASE_URL + '/auth';
export const SOCKET_URL = 'ws://${LOCAL_IP}:${PORT}';
export default { BACKEND_HTTP, API_BASE_URL, AUTH_API_URL, SOCKET_URL };`;
  fs.writeFileSync(envConfigPath, envContent, "utf8");

  // --- Generate socket-client.js singleton ---
  const socketJsPath = join(frontendJsDir, "socket-client.js");
  const socketContent = `// Auto-generated socket client for frontend
if (typeof window !== 'undefined') {
  if (!window.socket) {
    try {
      window.socket = (typeof io !== 'undefined') ? io('${BACKEND_HTTP}') : null;
    } catch (e) {
      window.socket = null;
    }
  }
}
export default window.socket;`;
  fs.writeFileSync(socketJsPath, socketContent, "utf8");

  console.log("✅ Auto-sync: env-config.js + socket-client.js updated successfully.");
} catch (e) {
  console.warn("⚠ Auto-sync script failed:", e.message);
}

// ==============================================
// 🧩 Dependencies
// ==============================================
import express from "express";
import cors from "cors";
import helmet from "helmet";
import morgan from "morgan";
import bodyParser from "body-parser";
import mongoose from "mongoose";
import { createServer } from "http";
import { Server as IOServer } from "socket.io";
import { connectToMongoDB } from "./src/config/db.js";
import PendingOrder from "./src/models/PendingOrder.js";

// ==============================================
// ⚙ Express + HTTP Setup
// ==============================================
const app = express();
const httpServer = createServer(app);

// ==============================================
// 🛡 Security - Helmet + CORS Configuration
// ==============================================
app.use(
  helmet({
    contentSecurityPolicy: false, // ✅ disable strict CSP for LAN
    crossOriginEmbedderPolicy: false,
    crossOriginResourcePolicy: { policy: "cross-origin" },
  })
);

app.use(
  cors({
    origin: [
      `http://${LOCAL_IP}:${PORT}`,
      "http://localhost:5555",
      "http://127.0.0.1:5555",
    ],
    methods: ["GET", "POST", "PUT", "DELETE"],
    credentials: true,
  })
);

// ✅ Prevent 416 errors + fix browser isolation
app.disable("crossOriginOpenerPolicy");
app.use((req, res, next) => {
  res.setHeader("Accept-Ranges", "bytes");
  res.setHeader("Origin-Agent-Cluster", "?0");
  res.setHeader("Cache-Control", "public, max-age=86400");
  res.setHeader("Access-Control-Allow-Origin", "*");
  next();
});

// ==============================================
// 🌐 HTTPS Redirect for Production (safe)
// ==============================================
if (process.env.NODE_ENV === "production") {
  app.use((req, res, next) => {
    if (req.headers["x-forwarded-proto"] !== "https") {
      return res.redirect(`https://${req.headers.host}${req.url}`);
    }
    next();
  });
}

// ==============================================
// 🧱 Middleware Setup
// ==============================================
app.use(bodyParser.json({ limit: "8mb" }));
app.use(bodyParser.urlencoded({ extended: true }));
app.use(morgan("dev"));

// ==============================================
// 🧱 Static Files
// ==============================================
const publicPath = resolve(__dirname, "public");
const eventFrontendPath = resolve(__dirname, "../event-frontend");
// ===== FIX: Proper MP3 streaming for audio files =====
const audioDir = resolve("../event-frontend/audio");

app.get("/event-frontend/audio/:file", async (req, res) => {
  const fs = (await import("fs")).default;
  const path = (await import("path")).default;
  const filePath = path.join(audioDir, req.params.file);
  if (!fs.existsSync(filePath)) return res.status(404).end();

  const stat = fs.statSync(filePath);
  const fileSize = stat.size;
  const range = req.headers.range;

  if (range) {
    const parts = range.replace(/bytes=/, "").split("-");
    const start = parseInt(parts[0], 10);
    const end = parts[1] ? parseInt(parts[1], 10) : fileSize - 1;

    if (start >= fileSize || end >= fileSize) {
      res.status(416).send("Range Not Satisfiable");
      return;
    }

    const chunkSize = end - start + 1;
    const file = fs.createReadStream(filePath, { start, end });
    const head = {
      "Content-Range": `bytes ${start}-${end}/${fileSize}`,
      "Accept-Ranges": "bytes",
      "Content-Length": chunkSize,
      "Content-Type": "audio/mpeg",
    };
    res.writeHead(206, head);
    file.pipe(res);
  } else {
    res.setHeader("Accept-Ranges", "bytes");
    res.setHeader("Content-Type", "audio/mpeg");
    fs.createReadStream(filePath).pipe(res);
  }
});



app.use(express.static(publicPath));
app.use("/event-frontend", express.static(eventFrontendPath));
app.get("/", (req, res) => res.redirect("/event-frontend/home.html"));

/// Fix MP3 range streaming issue
app.get("/event-frontend/audio/:file", (req, res, next) => {
  res.setHeader("Accept-Ranges", "bytes");
  next();
});

// ==============================================
// 🔗 API Routes
// ==============================================
import authRoutes from "./src/routes/authRoutes.js";
import vendorRoutes from "./src/routes/vendorRoutes.js";
import riderRoutes from "./src/routes/riderRoutes.js";
import paymentRoutes from "./src/routes/paymentRoutes.js";
import emailRoutes from "./src/routes/emailRoutes.js";
import authV2 from "./src/routes/auth.routes.js";
import productV2 from "./src/routes/product.routes.js";
import orderV2 from "./src/routes/order.routes.js";
import paymentV2 from "./src/routes/payment.routes.js";
import webhookV2 from "./src/routes/webhook.routes.js";
import vendorV2 from "./src/routes/vendor.routes.js";
import riderV2 from "./src/routes/rider.routes.js";
import adminV2 from "./src/routes/admin.routes.js";
import subscriptionV2 from "./src/routes/subscription.routes.js";
import kycV2 from "./src/routes/kyc.routes.js";
import notificationsV2 from "./src/routes/notification.routes.js";
import dispatcherRoutes from "./src/routes/dispatcher.routes.js";
import reviewRoutes from "./src/routes/review.routes.js";

app.use("/auth", authRoutes);
app.use("/vendors", vendorRoutes);
app.use("/riders", riderRoutes);
app.use("/payments", paymentRoutes);
app.use("/api/email", emailRoutes);
app.use("/api/auth", authV2);
app.use("/api/products", productV2);
app.use("/api/orders", orderV2);
app.use("/api/payments", paymentV2);
app.use("/api/paystack", webhookV2);
app.use("/api/vendors", vendorV2);
app.use("/api/riders", riderV2);
app.use("/api/admin", adminV2);
app.use("/api/subscriptions", subscriptionV2);
app.use("/api/kyc", kycV2);
app.use("/api/notifications", notificationsV2);
app.use("/api/dispatchers", dispatcherRoutes);
app.use("/api/reviews", reviewRoutes);

// ==============================================
// ⚡ Socket.IO Setup
// ==============================================
const io = new IOServer(httpServer, {
  cors: { origin: "*", methods: ["GET", "POST"] },
  transports: ["websocket", "polling"],
});
app.set("io", io);
globalThis.io = io;

io.on("connection", (socket) => {
  console.log("🟢 Socket connected:", socket.id);
  socket.emit("welcome", { message: "Connected to QuickServe socket!" });
  socket.on("disconnect", () => console.log("🔴 Socket disconnected:", socket.id));
});

// ==============================================
// 🚀 Start Server
// ==============================================
connectToMongoDB()
  .then(async () => {
    try {
      const coll = mongoose.connection.collection("pendingorders");
      await coll.createIndex({ paymentReference: 1 }, { unique: false });
      console.log("✅ PendingOrder index ensured.");
    } catch (e) {
      console.warn("⚠ Could not adjust PendingOrder indexes:", e.message);
    }

    httpServer.listen(PORT, "0.0.0.0", () => {
      console.log(`🚀 QuickServe API running on ${BACKEND_HTTP}`);
      console.log(`📱 Access from phone: ${BACKEND_HTTP}`);
      console.log("✅ Helmet + HTTPS + Audio fixes applied successfully.");
      console.log("🧭 Waiting for connections...");
    });
  })
  .catch((err) => {
    console.error("❌ Failed to start server:", err.message);
    process.exit(1);
  });

export { app, httpServer };