// Auto-generated by QuickServe backend
export const BACKEND_HTTP = 'http://192.168.15.104:5555';
export const API_BASE_URL = BACKEND_HTTP + '/api';
export const AUTH_API_URL = API_BASE_URL + '/auth';
export const SOCKET_URL = 'ws://192.168.15.104:5555';
export default { BACKEND_HTTP, API_BASE_URL, AUTH_API_URL, SOCKET_URL };