name: Flutter CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
      - '.github/workflows/flutter-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
      - '.github/workflows/flutter-ci.yml'

jobs:
  analyze-and-test:
    name: Analyze and Test (Flutter frontend)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run tests (if any)
        shell: bash
        run: |
          if [ -d "test" ] && [ "$(ls -A test)" ]; then
            flutter test -r expanded
          else
            echo "No Flutter tests found"
          fi
